# Generated by Django 4.1.3 on 2023-01-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directors',
            name='name',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
