# Generated by Django 4.1.3 on 2023-01-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_directors_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='contentRate',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
